### ISSUE TITLE
Issue with `gsutil_cp()` destination path

### ISSUE THREAD

**Issue by Kayla-Morrell** [Bioconductor/AnVIL#39] opened 2021-08-04 15:57 UTC
The destination path in `gsutil_cp` needs to be quoted to allow for spaces in the file path.

```
## the path to the file on the google bucket
gs_paths <- "gs://fc-40a5300a-767d-496b-ad9d-9a1904f62156/6710b4df-403e-43c3-a294-ef367882d9bb/salmon/0d35f1f1-cbab-46c6-ad47-1534456e6b8e/call-salmon_quant/shard-0/DRR016125_1.tar.gz"
## the destination
getwd()
> /home/jupyter/notebooks/Bioconductor-Workflow-DESeq2 copy/safe
AnVIL::gsutil_cp(gs_paths, getwd())
```

This results in the following error:
```
Error: 'gsutil -m cp gs://fc-40a5300a-767d-496b-ad9d-9a1904f62156/6710b4df-403e-43c3-a294-ef367882d9bb/salmon/0d35f1f1-cbab-46c6-ad47-1534456e6b8e/call-salmon_quant/shard-0/DRR016125_1.tar.gz /home/jupyter/notebooks/Bioconductor-Workflow-DESeq2 copy/safe' failed:
  CommandException: Destination URL must name a directory, bucket, or bucket subdirectory for the multiple source form of the cp command.
```

**Comment by mtmorgan** [comment] 2021-08-05 16:02
The problem is the space in the workspace name (and hence file path). This is fixed in https://github.com/Bioconductor/AnVIL/commit/e835a40489b6bc33dc0ba76a0ef15c79465a1230 but in general it seems like spaces in workspace names can be problematic and 'best practice' is to clone without spaces...

**Closed** 2021-08-05 16:38 UTC
