### ISSUE TITLE
gsutil_cp double-quotes inputs after v1.13.7

### ISSUE THREAD

**Issue by smgogarten** [Bioconductor/AnVIL#89] opened 2023-09-05 20:56 UTC
The latest updates to `gsutil_cp` seem to have introduced double-quoting of inputs resulting in errors:
```
> gsutil_cp("gs://fc-547ef6ab-c518-416f-8e0f-26ab98009f30/gsr_analysis_table.tsv", ".")
Error in gsutil_cp("gs://fc-547ef6ab-c518-416f-8e0f-26ab98009f30/gsr_analysis_table.tsv",  : 
  object '"gs://fc-547ef6ab-c518-416f-8e0f-26ab98009f30/gsr_analysis_table.tsv"' not found
> x <- "gs://fc-547ef6ab-c518-416f-8e0f-26ab98009f30/gsr_analysis_table.tsv"
> gsutil_cp(x, ".")
Error in gsutil_cp(x, ".") : object '"."' not found
> y <- "."
> gsutil_cp(x, y)
Error in gsutil_cp(x, y) : object 'source_is_uri' not found
```

**Comment by mtmorgan** [comment] 2023-09-05 21:43
I can see where this is coming from
```
> gsutil_cp(x, y)
Error in gsutil_cp(x, y) : object 'source_is_uri' not found
```
but the other, e.g., 
```
> gsutil_cp(x, ".")
Error in gsutil_cp(x, ".") : object '"."' not found
```
is a head-scratcher and I don't see it locally
```
> x <- "gs://fc-547ef6ab-c518-416f-8e0f-26ab98009f30/gsr_analysis_table.tsv"
> gsutil_cp(x, ".")
Error in gsutil_cp(x, ".") : object 'source_is_uri' not found
```
Is this unique to RStudio? (You can use the terminal in RStudio to launch R from the command line, for instance; if an RStudio  issue what version of RStudio?)

**Comment by LiNk-NY** [comment] 2023-09-05 21:53
Thanks Martin, I have merged https://github.com/Bioconductor/AnVIL/pull/88 which addresses the first issue. 
I am trying to reproduce

```r
Error in gsutil_cp(x, ".") : object '"."' not found
```

@smgogarten Is there a public example file (`.tsv`) we can use for testing? 

*Update*: I was unable to reproduce with a public resource, e.g.,:

```r
gsutil_cp("gs://firecloud-tcga-open-access/tcga/dcc/coad/clin__bio__intgen_org__Level_1__auxiliary__clin/intgen.org_COAD.bio.Level_1.76.17.0/TCGA-A6-2671.clin.txt", ".")
```

Perhaps the quotes in your original command were encoded in a way that R does not understand?

**Comment by smgogarten** [comment] 2023-09-06 16:38
Here's a reproducible example:
```
docker run -it us.gcr.io/broad-dsp-gcr-public/anvil-rstudio-bioconductor:3.17.0 R
> BiocManager::install("Bioconductor/AnVIL", ref="b95f37e") # commit prior to last update
> library(AnVIL)
> x <- "gs://fc-547ef6ab-c518-416f-8e0f-26ab98009f30/gsr_analysis_table.tsv"
> gsutil_cp(x, ".")
Error in gsutil_cp(x, ".") : object '"."' not found
```

I don't get the error with `ref="a51d008"` (version 1.13.6) or with the latest version, so maybe your most recent commit fixed it?

**Comment by mtmorgan** [comment] 2023-09-06 17:18
Neat; I did
```
> f = function(x) y
> f(".")
Error in f(".") : object '"."' not found
> R.version.string
[1] "R version 4.3.0 (2023-04-21)"
```
I think this is a bug in that version of R (I can replicate this outside the docker container). In a later version I have
```
> f = function(x) y
> f(".")
Error in f(".") : object 'y' not found
> R.version.string
[1] "R version 4.3.1 Patched (2023-08-16 r84986)"
```

**Comment by smgogarten** [comment] 2023-09-06 17:33
That docker image is the default environment for all RStudio instances in AnVIL. Do you know who is responsible for updates?

**Comment by mtmorgan** [comment] 2023-09-06 17:37
@almahmoud is responsible on our end for the docker images, but the deployment goes through the Broad / Terra.

**Comment by almahmoud** [comment] 2023-09-06 18:13
Thank you @smgogarten for taking the time to report the issue, it's really helpful!

@mtmorgan @LiNk-NY Just to be clear, do we need the new image to include 2 changes, namely both a new version of `AnVIL` package (and which version? Was it fixed in release or devel on Bioc git? I can install a specific version from bioc source or github as well if desired), and an updated version of R?

The process for updating on AnVIL will take a bit of time to propagate on Terra side, but I can start the rebuilding asap on our side

**Comment by LiNk-NY** [comment] 2023-09-06 21:33
@almahmoud 
The newest version of `AnVIL` in devel is `1.13.9`. It doesn't look like this version has been built on bioc-devel yet so you may have to install from GitHub (`devel` branch).

There were no changes in release.

Yes, the main issue was a bug in R which seems to have been resolved in R `4.3.1`. 

Thanks!

**Comment by mtmorgan** [comment] 2023-09-08 01:02
For what it's worth the bug in R was [reported](https://bugs.r-project.org/show_bug.cgi?id=18519) and fixed (https://github.com/wch/r-source/commit/bb9c86072e338adfabac01de3fe014ec264a4542, https://github.com/wch/r-source/commit/441b7c59c06708a679b0d9ab861e8ade1c7a326b), but without a NEWS entry.

**Comment by almahmoud** [comment] 2023-09-12 19:46
You can use the fixed version in AnVIL With a Custom Environment using container `ghcr.io/anvilproject/anvil-rstudio-bioconductor:3.17.1-dev`
The production default will be changed within the next weeks (Terra folks control the timeline for that)

**Comment by almahmoud** [comment] 2023-09-12 19:47
I'll mark this as fixed and close the issue since the dev container is rebuilt and has been tested in Terra, please re-open if I missed anything and/or if there are any other issues!

**Closed as completed by almahmoud** 2023-09-12 19:47 UTC
